Update on_pr.yml

diff --git a/.github/workflows/on_pr.yml b/.github/workflows/on_pr.yml
--- a/.github/workflows/on_pr.yml
+++ b/.github/workflows/on_pr.yml
@@ -9,10 +9,16 @@ jobs:
       image: seika/cxx-test:latest
     steps:
       - uses: actions/checkout@v3
-      - name: Validate branch name
+      - name: Validate branch and task names
         run: |
-          if [[ ! $GITHUB_HEAD_REF =~ ^[a-z]+-[a-z]+-task[0-9]+$ ]]; then
-            echo "::error::Branch name must be in format 'surname-name-taskN'"
+          if [[ ! $GITHUB_HEAD_REF =~ ^[a-z]+-[a-z]+-task[ehm][1-9]$|^[a-z]+-[a-z]+-task[ehm]10$ ]]; then
+            echo "::error::Branch name must be in format 'surname-name-task{e,m,h}{1..10}'"
+            exit 1
+          fi
+
+          TASK_DIR="members/${GITHUB_HEAD_REF%-task*}/task${GITHUB_HEAD_REF##*-task}"
+          if [ ! -d "$TASK_DIR" ]; then
+            echo "::error::Task directory $TASK_DIR not found"
             exit 1
           fi
 
@@ -23,8 +29,9 @@ jobs:
       image: seika/cxx-test:latest
     steps:
       - uses: actions/checkout@v3
-      - name: Build
+      - name: Build task
         run: |
-          cd members/${GITHUB_HEAD_REF%-task*}
+          TASK_DIR="members/${GITHUB_HEAD_REF%-task*}/task${GITHUB_HEAD_REF##*-task}"
+          cd "$TASK_DIR"
           mkdir -p build && cd build
           cmake .. && make
